# $BOONTADATA_DOCKER_REGISTRY/boontadata/sstreamworker
#
# VERSION   0.1

FROM $BOONTADATA_DOCKER_REGISTRY/boontadata/sstreambase:0.1

MAINTAINER boontadata <contact@boontadata.io>

CMD [ "/bin/bash" ]
